FROM golang:latest
VOLUME /tmp
ARG REGION_ARG=us-east-2
ARG ACCESS_ARG
ARG SECRET_ARG
ENV AWS_REGION=$REGION_ARG
ENV AWS_ACCESS_KEY=$ACCESS_ARG
ENV AWS_SECRET_KEY=$SECRET_ARG
COPY *.go main.go
RUN CGO_ENABLED=0 GOOS=linux go build main.go
EXPOSE 8080
CMD ["/main"]